logging:
  level:
    org.springframework: INFO

spring:
  profiles:
    #active: h2initdata
    #active: h2initbycodedata
    active: TestRepo
  h2:
    console.enabled: true
  sql:
    init:
      platform: h2
      continue-on-error: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        show_sql: true
        use_sql_comments: true
        format_sql: true
---
spring:
  profiles: h2initbycodedata, TestRepo
  sql.init.mode: never
  jpa.hibernate.ddl-auto: create-drop
---
spring:
  profiles: h2initdata
  sql.init.mode: always
  jpa.hibernate.ddl-auto: none
---